version: '3.9'
networks:
  stat-stop:
volumes:
  database-volume:
  logs:
services:
  database:
    image: mysql:latest
    healthcheck:
      test: ["CMD", "ls"]
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: statstopDB
      MYSQL_USER: statstop
      MYSQL_PASSWORD: statstop@123
    volumes:
      - database-volume:/var/lib/mysql
    networks:
      - stat-stop

  backend:
    image: statstop/statstop_backend:latest
    environment:
      DB_URL: jdbc:mysql://database:3306/StatStopDB?createDatabaseIfNotExist=true
      DB_USERNAME: root
      DB_PASSWORD: root@123
    volumes:
      - logs:/logs
    networks:
      - stat-stop
    ports:
      - "8085:8085"
    depends_on:
      database:
        condition: service_healthy
  frontend:
    image: statstop/statstop_frontend:latest
    networks:
      - stat-stop
    ports:
      - "3005:3000"
    depends_on:
      - database


